version: '3.4'

services:
  RabbitMQ:
    image: rabbitmq:3.10.7-management
    container_name: RabbitMQ
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 500000000
    volumes:
       - ./rabbitmq:/var/lib/rabbitmq
      
volumes:
    rabbitmq: